server:
  port: 8762

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
     username: suyongming
     password: 476231418
     driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    database: 0
#    host: 192.168.50.20
#    port: 6379
#    timeout: 0
#    password: 123456
#    jedis:
#      pool:
#        max-idle: 8
#        max-wait: -1

#某机构需要的sms
SMS:
  HOST: 192.168.0.215
  ACCOUNTID: 555580001
  PASSWORD: cool1226


mybatis:
  mapper-locations: classpath:mapper/*.xml

preposition:
  baseUrl: ${PREPOSITION_URL:not_null}
#  baseUrl: http://wa.zs-hospital.sh.cn:8700/PhyAppWS/PhyAppWS.asmx?wsdl

baseModelParam:
#  INSTITUTION_CODE: 190102
  INSTITUTION_CODE: ${PREPOSITION_HOS_CODE:not_null}
